spring:
  application:
    name: catalog-mongo
  data:
    mongodb:
      uri: mongodb://localhost:27017/?retryWrites=true&w=majority
      database: CatalogDB
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
    host: localhost
    port: 6379
